In [ ]:
#each key, value pair will be saved in an array as the node of a linked list
class Node:
 def __init__(self, element, next):
  self.element=element
  self.next=next
def hash_function(key):
  return key % 5 #hardcoding lemgth of array to 5
original_array=[(5,"apple"), (3, "orange"), (2, "cherry"), (12,"banana"), (23, "grapes")]
indexed_array=[None]*5
for i in range(len(original_array)):
  key=original_array[i][0]
  new_key=hash_function(key)
  node=Node(original_array[i],None)
  if indexed_array[new_key]==None:
   indexed_array[new_key]=node
  else:
   head=indexed_array[new_key]
   node.next=head
   indexed_array[new_key]=node
print(indexed_array)
key_to_search=int(input())
hashed_key=hash_function(key_to_search)
linked_list_at_key=indexed_array[hashed_key]
temp=linked_list_at_key
while temp!=None:
 if temp.element[0]==key_to_search:
  print(temp.element[1])
 temp = temp.next

[<__main__.Node object at 0x7eb11d3c31f0>, None, <__main__.Node object at 0x7eb11d3c2fe0>, <__main__.Node object at 0x7eb11d3c1630>, None]
2
cherry


Quiz 2 Question 1:

In [ ]:
class Node:
  def __init__(self, element, next):
    self.element = element
    self.next = next
class Stack:
  def __init__(self):
    self.top = None # an empty stack
  def push(self, element):
    if self.top == None:
      self.top = Node(element, None)
    else:
      node = Node(element, None)
      node.next = self.top
      self.top = node
  def pop(self):
    if self.top == None:
      return -1  #this is error
    else:
      popped_node = self.top
      self.top = popped_node.next
      popped_node.next = None
      return popped_node.element
  def peek(self):
    if self.top!= None:
      return self.top.element
    return -1
  def empty(self):
    return self.top == None
def mergeIntervals(set_of_intervals):
  res_stack = Stack()
  res_stack.push(set_of_intervals[0])
  for i in range(1, len(set_of_intervals)):
    current_start, current_end=res_stack.peek()
    if set_of_intervals[i][0]<=current_end: #overlap
      if current_end<set_of_intervals[i][1]:
       res_stack.pop()               #pop current
       res_stack.push((current_start,set_of_intervals[i][1]))
    else:
      res_stack.push(set_of_intervals[i])
  while res_stack.empty()!= True:
   print(res_stack.pop())
mergeIntervals([(1, 5), (2, 3), (4, 6), (7, 8), (8, 10), (12, 15)])

(12, 15)
(7, 10)
(1, 6)


Quiz 2 Question 2:

In [ ]:
class Node:
  def __init__(self, element, next):
    self.element = element
    self.next = next
def count_elements(head):
  count=0
  temp=head
  while temp!= None:
    count+=1
    temp=temp.next
  return count
def nodeAt(head, idx):
  temp=head
  c=count_elements(head)
  current_idx = 0
  if idx<0  or idx>= c:
    return -1
  while temp!= None:
    if current_idx == idx:
      return temp
    current_idx +=1
    temp = temp.next
def insertElement(head, element, idx ):
  if idx == 0:
    node = Node(element, head)
    head = node
    return head
  elif count_elements(head) == idx:
    node = Node(element, None)
    prev_node = nodeAt(head, idx -1)
    prev_node.next = node
    return head
  elif 0<idx<count_elements(head):
    node=Node(element, None)
    prev_node=nodeAt(head, idx-1)
    node.next=prev_node.next
    prev_node.next=node
    return head
  else:
    return -1
#drivercode
def swapElements(head, k):
  len = count_elements(head)

  node1 = nodeAt(head, k-1)
  node2 = nodeAt(head, len - k)

  if k == 1:
    prev_node2 = nodeAt(head, len - k -1) #the node before node2
    prev_node2.next = node1 #placing node1
    node2.next = node1.next #placing node2
    node1.next = None

    return node2 #node2 is the new head

  else:

    temp1next = node1.next #saving the address of the node AFTER node 1
    temp2next = node2.next #saving the address of the node AFTER node 2

    prev_node1= nodeAt(head, k-2) #retrieving the node BEFORE node 1
    prev_node2= nodeAt(head, len - k -1) #retrieving the node BEFORE node 2

    prev_node1.next = node2 # bringing node2 in place of node1
    prev_node2.next = node1 # bringing node1 in place of node2

    node2.next = temp1next #node2 now points to the node that was initially after node1
    node1.next = temp2next #node1 now points to the node that was initially after node2

    return head
head = Node(5, None)

head = insertElement(head,4, 0)

head = insertElement(head, 8, 1)

head = insertElement(head, 10, 3)

head = insertElement(head, 5, 2)

temp = head

while temp!= None:
  print(temp.element)
  temp = temp.next
print("---------")
head = swapElements(head, 2)

temp = head

while temp!= None:
  print(temp.element)
  temp = temp.next

4
8
5
5
10
---------
4
5
5
8
10


Quiz 1 Question 2:

In [ ]:
import numpy as np
img = [[1,1,0],[1,0,1],[0,0,0]]
def flipAndInvertImage(image):
  rows=len(image)
  new_img=np.zeros((rows,rows), dtype = int)
  for i in range(rows):
    for j in range(rows):
      new_img[i][rows-1-j]=image[i][j]
  for i in range(rows):
   for j in range(rows):
    if new_img[i][j]== 0:
     new_img[i][j]= 1
    else:
     new_img[i][j]= 0
  return new_img
print(flipAndInvertImage(img))

[[1 0 0]
 [0 1 0]
 [1 1 1]]


Quiz 1 Question 1:

In [ ]:
def rotateLeft(array):

  l = len(array)

  temp = array[0]

  for i in range(0, l-1):

    array[i] =array[i+1]

  array[l-1] = temp
  return array

def printTime(hours, minutes, jump):

  change_hours = jump // 60
  change_minutes = jump % 60

  for h in range(change_hours):
    hours = rotateLeft(hours)

  for m in range(change_minutes):
    minutes = rotateLeft(minutes)

  if minutes[0] >= 10:
    time = str(hours[0]) + ":" + str(minutes[0])
  else:
    time = str(hours[0]) + ":0" + str(minutes[0])


  return time

hours = np.arange(1, 13)
minutes = np.arange(60)

printTime(hours, minutes, 719)

'12:59'

In [ ]:
class Node:
  def __init__(self, element, next):
    self.element = element
    self.next = next
class Stack:
  def __init__(self):
    self.top = None # an empty stack
  def push(self, element):
    if self.top == None:
      self.top = Node(element, None)
    else:
      node = Node(element, None)
      node.next = self.top
      self.top = node
  def pop(self):
    if self.top == None:
      return -1  #this is error
    else:
      popped_node = self.top
      self.top = popped_node.next
      popped_node.next = None
      return popped_node
#reversing a string using a stack
word = "ABCD"
new_stack = Stack()
for i in range(len(word)):
  new_stack.push(word[i])
while new_stack.top != None:
  letter = new_stack.pop()
  print(letter.element)




D
C
B
A


driver code

In [ ]:
class Node:
  def __init__(self, element, next):
    self.element = element
    self.next = next

def count_elements(head):
  count = 0
  temp = head
  while temp!= None:
    count += 1
    temp = temp.next
  return count

def nodeAt(head, idx):
  temp = head
  c = count_elements(head)
  current_idx = 0
  if idx<0  or idx >= c:
    return -1

  while temp!= None:
    if current_idx == idx:
      return temp
    current_idx +=1
    temp = temp.next

def insertElement(head, element, idx ):

  if idx == 0:
    node = Node(element, head)
    head = node
    return head

  elif count_elements(head) == idx:
    node = Node(element, None)
    prev_node = nodeAt(head, idx -1)
    prev_node.next = node
    return head

  elif 0 < idx < count_elements(head):
    node = Node(element, None)
    prev_node = nodeAt(head, idx-1)
    node.next = prev_node.next
    prev_node.next = node
    return head

  else:
    return -1



In [ ]:

head = Node(5, None)

head = insertElement(head,4, 0)

head = insertElement(head, 8, 1)

head = insertElement(head, 10, 3)

temp = head

while temp!= None:
  print(temp.element)
  temp = temp.next


4
8
5
10


In [ ]:
import numpy as np

def shiftRight(array):
  l=len(array)
  for i in range(l-1, 0, -1):
    array[i]=array[i-1]
  array[0]=0
  return array
print(shiftRight(np.array([1,2,3,4])))
def shiftRightbyK(array,K):
  for i in range(K):
    array=shiftRight(array)
  return array
print(shiftRightbyK(np.array([1,2,3,4]),3))


array([0, 0, 0, 1])

In [ ]:
def shiftLeft(array):
  l=len(array)
  for i in range(0, l-1):
    array[i]=array[i+1]
  array[l-1]=0
  return array
print(shiftLeft(np.array([1,2,3,4])))
def removeByIndex(array, index):
  l=len(array)
  for i in range(index, l-1):
    array[i]=array[i+1]
  array[l-1]=0
  return array
print(removeByIndex(np.array([1,2,3,4]), 2))
def removeAllOccurancesByValue(array, value):
  l = len(array)
  for i in range(l):
   while array[i] == value:
    array = removeByIndex(array, i)
  return array
print(removeAllOccurancesByValue(np.array([1,2,2,3,4,2,2,2]), 2))

[2 3 4 0]
[1 2 4 0]
[1 3 4 0 0 0 0 0]


In [ ]:
import numpy as np
a = np.array([[1,2,3], [4,5,6]]) #m rows, n cols
b = np.array([[10, 11], [3,5], [1, 2]]) #n rows, p cols
c = np.zeros((2,2)) #m x p
for i in range(2): # m ( no. of rows of c)
  for j in range(2) : #p (no. of cols of c)
    for k in range(3) : # n (no of cols of a or no of rows in b)
      c[i][j]+=(a[i][k]*b[k] [j])
print(c)


[[19. 27.]
 [61. 81.]]


In [ ]:
a = np.array([[1,2,3],[1,2,3], [1,2,3], [1,2,3]]) # 4 rows, 3 columns (m x n )
b = np.array([[5,6],[5,6],[5,6]]) # 3 rows, 2 columns (n x p)
c = np.zeros((4,2)) # (m x p)
for i in range(4): # m
  for j in range(2): # p
    for k in range(3): #n
      c[i][j]+=a[i][k]*b[k][j]
print(c)

[[30. 36.]
 [30. 36.]
 [30. 36.]
 [30. 36.]]
