###Basics

In [ ]:
def iteration(source):  # iteration
  for i in range(len(source)):
    print(source[i])


def reverse_iteration(source):  # reverse iteration
  for i in range(len(source)-1, -1, -1):
    print(source[i])


def copy_array(source):  # copying array
  new_array = [None]*len(source)  # generating an array
  for i in range(len(source)):
    new_array[i] = source[i]
  return new_array


def resize_array(old_array, new_cap):   # resizing array
  new_array = [None]*new_cap
  for i in range(len(old_array)):
    new_array[i] = old_array[i]
  return new_array


def reverse_in_place(arr):
  for i, j in zip(range(len(arr)), range(len(arr)-1, -1, -1)):
    if i > j:
      break
    else:
      temp = arr[i]
      arr[i] = arr[j]
      arr[j] = temp
  print(arr)


def shift_left(arr):
  for i in range(1, len(arr)):
    arr[i-1] = arr[i]
  arr[len(arr)-1] = None
  return arr


def shift_right(arr):
  for i in range(len(arr)-1, 0, -1):
    arr[i] = arr[i-1]
  arr[0] = None
  return arr


def rotate_left(arr):
  for i in range(1, len(arr)):
    arr[i-1] = arr[i]
  arr[len(arr)-1] = arr[0]
  return arr

###Question - 01

In [ ]:
size1, size2 = input().split(' ')
size1, size2 = int(size1), int(size2)

arr1 = [None]*size1
l1 = input().split(' ')
for i in range(len(l1)):
  arr1[i] = int(l1[i])

arr2 = [None]*size2
l2 = input().split(' ')
for i in range(len(l2)):
  arr2[i] = int(l2[i])

union_arr = [None]*(size1+size2)
count = 0
for i in range(len(arr1)):
  union_arr[i] = arr1[i]
  count += 1

for j,k in zip(range(count, len(arr2)+count), range(len(arr2))):
  if arr2[k] not in union_arr:
    union_arr[j] = arr2[k]

c = 0
for i in range(len(union_arr)):
  if union_arr[i] != None:
    c +=1
print(c)

###Question - 02

In [ ]:
import numpy as np

def arrange(arr):
  n = len(arr)
  pos, neg, new = np.zeros(n, dtype = int), np.zeros(n, dtype = int), np.zeros(n, dtype = int)

  neg_start = 0
  for i in range(n):
    if arr[i] > 0:
      pos[i] = arr[i]
      neg_start = i+1

  for i in range(n):
    if arr[i] < 0:
      neg[i] = arr[i]

  for i in range(neg_start, n):
    initiate = 0
    for j in range(initiate+1, len(neg)):
      pos[i] = neg[j]
      initiate = j
      break
  return pos


e1, e2 = np.array([1, -1, 3, 2, -7, -5, 11, 6]), np.array([-5, 7, -3, -4, 9, 10, -1, 11])
print(arrange(e1))
print(arrange(e2))

[ 1  0  3  2  0  0 11  6]
[ 0  7  0  0  9 10  0 11]


###Question - 03

In [ ]:
import numpy as np

def sum_subArray(arr, sum):

  for i in range(len(arr)):
    current = arr[i]

    for j in range(i+1, len(arr)):
      current += arr[j]
      if current == sum:
        return f'{i+1} {j+1}'

  return -1


t1 = np.array([1,2,3,7,5])
print(sum_subArray(t1, 12))

t2 = np.array([1,2,3,4,5,6,7,8,9,10])
print(sum_subArray(t2, 15))

2 4
1 5


###Question - 15

In [ ]:
import numpy as np

def median(arr1, arr2):
  new = np.zeros(len(arr1) + len(arr2), dtype = int)
  start = 0
  for i in range(len(arr1)):
    if arr1[i] < arr2[0]:
      new[i] = arr1[i]
      start = i + 1

  s = 0
  for i in range(start, len(new)):
    for k in range(s, len(arr2)):
      new[i] = arr2[k]
      s = k+1
      start2 = i+1
      break

  for i in range(start, len(arr1)):
    for j in range(start2, len(new)):
      new[j] = arr1[i]

  if len(new) % 2 != 0:
    return new[len(new)//2]
  else:
    i = (len(new) + 1) // 2
    return (new[i] + new[i-1]) / 2

num1 = np.array([1, 3])
num2 = np.array([2])
returned_val = median(num1, num2)
print('{:.5f}'.format(returned_val))

2.00000


###Question - 09

In [ ]:
import numpy as np

def majority_element(arr): # appears more that N/2 times in arr
  n = len(arr) // 2
  for i in range(len(arr)):
    count = 0
    for j in range(i+1, len(arr)):
      if arr[i] == arr[j]:
        count += 1
        if n > count:
          return arr[i]
  return -1


n = int(input('N = '))
array = np.zeros(n, dtype = int)
for i in range(n):
  array[i] = int(input())
returned_value = majority_element(array)
print(f'Returned Value: {returned_value}')

N = 10
1
3
4
5
6
2
2
2
2
2
Returned Value: 2


###Question - 08

In [ ]:
import numpy as np

def wave(arr):
  n = len(arr)

  if n % 2 != 0:
    for i in range(0, n-1, 2):
      temp = arr[i]
      arr[i] = arr[i+1]
      arr[i+1] = temp
  else:
    for i in range(0, n, 2):
      temp = arr[i]
      arr[i] = arr[i+1]
      arr[i+1] = temp

  return arr


seq1, seq2 = np.array([1, 2, 3, 4, 5]), np.array([2, 4, 7, 8, 9, 10])
print(wave(seq1))
print(wave(seq2))

[2 1 4 3 5]
[ 4  2  8  7 10  9]


###Question 07
Preprocessing an array [Water trapped problem in co-ordinate system]

In [1]:
import numpy as np

def return_min(a, b): # helper function
  if a < b:
    return a
  else:
    return b

def water_trapped(arr):
  n = len(arr)
  left_right, right_left = arr.copy(), arr.copy()

  for i in range(n-1): # left --> right preprocessing
    if left_right[i] > left_right[i+1]:
      left_right[i+1] = left_right[i]

  for j in range(n-1, -1, -1): # right --> left preprocessing
    if right_left[j-1] < right_left[j]:
      right_left[j-1] = right_left[j]

  # computing minimums of left_right[i] and right_left[i]
  trapped_water = 0
  for i in range(n):
    trapped_water += return_min(left_right[i], right_left[i]) - arr[i] # main formula for trapped water

  return trapped_water


example_1 = np.array([3, 0, 0, 2, 0, 4])
returned = water_trapped(example_1)
print(f'Example 1: {returned}')

example_2 = np.array([7, 4, 0, 9])
returned = water_trapped(example_2)
print(f'Example 2: {returned}')

example_3 = np.array([6, 9, 9])
returned = water_trapped(example_3)
print(f'Example 3: {returned}')

Example 1: 10
Example 2: 10
Example 3: 0


###Question 06
Sort ascending

In [ ]:
import numpy as np

def ascending(arr):
  n = len(arr)

  for i in range(n):
    for j in range(i+1, n):
      if arr[i] > arr[j]:
        temp = arr[i]
        arr[i] = arr[j]
        arr[j] = temp

  return arr


arr1, arr2 = ascending(np.array([0, 2, 1, 2, 0])), ascending(np.array([0, 1, 0]))
print(arr1)
print(arr2)

[0 0 1 2 2]
[0 0 1]


###Question 05

In [ ]:
import numpy as np

def kTH_smallest(arr, k):
  arr = ascending(arr)
  return arr[k-1]

t1 = np.array([7, 10, 4, 3, 20, 15])
print(kTH_smallest(t1, 3))

t2 = np.array([7, 10, 4, 20, 15])
print(kTH_smallest(t2, 4))

7
15
